import type { Metadata } from "next";
import Footer from "./components/Footer";
import Nav from "./components/Nav";
import "./globals.css";

export const metadata: Metadata = {
  title: "Manga Diary",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
